services:
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui
    volumes:
      - /Volumes/Data/zz_nobackup/development/openweb-ui/volumes/open-webui:/app/backend/data
    ports:
      - 8080:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped


